
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: pm

test:
  <<: *default
  database: pm_test

production:
  <<: *default
  database: pm_production

